version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/users.db
    restart: unless-stopped